[package]
name = "thresh"
version = "0.1.0"
description = "Tiny local continuous integration based on Github webhooks"
authors = ["gillchristian <gillchristiang@gmail.com>", "ndelvalle <nicolas.delvalle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
actix-web = "2.0.0"
chrono = "0.4"
env_logger = "0.7"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
shellexpand = "2.0"
toml = "0.5"
actix-files = "0.2.2"
clap = "2.33.1"
actix-service = "1.0.5"
futures = "0.3.5"
futures-util = "0.3.5"
serde_derive = "1.0.111"
hmac = "0.8.0"
sha-1 = "0.9.0"
rust-crypto = "0.2.36"
hex = "0.4.2"
openssl = "0.10.29"
