[[projects]]

username = "gillchristian"

repository = "tsplay.dev"

path = "~/dev/tsplay/server"

commands = [
  "docker pull gillchristian/tsplay:latest",
  "docker-compose down",
  "docker-compose up -d",
]

[[projects]]

username = "ndelvalle"

repository = "sarasa"

path = "~/code/sarasa"

commands = [
  "git pull",
  "cargo build",
  "cargo run --release",
]
